/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 scene.gltf 
Author: snafuj (https://sketchfab.com/snafuj)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/stryker-fe28759be4914e4a9ea52d73aa503a4e
Title: Stryker
*/

import React, {useRef} from 'react'
import {OrbitControls, useGLTF} from '@react-three/drei'

export default function Scene(props) {
    const {nodes, materials} = useGLTF('./src/models/btr/scene.gltf')
    return (
        <>
            <group {...props} dispose={null}>
                <group rotation={[-Math.PI / 2, 0, 0]}>
                    <lineSegments geometry={nodes.Object_2.geometry} material={materials.StrykerBody}/>
                    <mesh geometry={nodes.Object_3.geometry} material={materials.StrykerBody}/>
                    <mesh geometry={nodes.Object_4.geometry} material={materials.StrykerEquipments}/>
                    <mesh geometry={nodes.Object_5.geometry} material={materials.StrykerLights}/>
                    <mesh geometry={nodes.Object_6.geometry} material={materials.StrykerTurret}/>
                    <mesh geometry={nodes.Object_7.geometry} material={materials.StrykerWheel}/>
                    <mesh geometry={nodes.Object_8.geometry} material={materials.StrykerWheel}/>
                    <mesh geometry={nodes.Object_9.geometry} material={materials.StrykerWheel}/>
                    <mesh geometry={nodes.Object_10.geometry} material={materials.StrykerWheel}/>
                    <mesh geometry={nodes.Object_11.geometry} material={materials.StrykerWheel}/>
                    <mesh geometry={nodes.Object_12.geometry} material={materials.StrykerWheel}/>
                    <mesh geometry={nodes.Object_13.geometry} material={materials.StrykerWheel}/>
                    <mesh geometry={nodes.Object_14.geometry} material={materials.StrykerWheel}/>
                </group>
            </group>
        </>
    )
}

useGLTF.preload('./src/models/btr/scene.gltf')
